### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [jaakkolantero/fullstackopen_project#23]
# Katselmointi

Terve @jaakkolantero! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Kirjauduin sisään uutena käyttäjänä
- Päivitin käyttäjätietoni
- Lisäsin pitsoja ostoskoriin
- Lisäsin uuden tilauksen ja muokkasin tilaustietoja
- Tarkistin, että tilaus on tullut perille
- Kirjauduin ulos

### Kokemus

- Kokonaisuudessa käyttöliittymä on selkeä ja helppokäyttöinen, hyvää työtä!
- Rekisteröitymis- ja kirjautumistoiminnot ovat käyttökokemukseltaan tosi sulavat
- Ostoskori vaikuttaa tyhjentyvän, kun vaihtaa sivua. Lisäksi ostoskori tyhjenee tilauksen jälkeen vasta kun sivu on päivitetty
- Tilauksen yhteydessä tilaustiedot tulee täyttää vaikka käyttäjätiedot olisi täytetty. Ehkä tilaustiedot voisi olla oletusarvoisesti käyttäjätiedot?
- Keskeneräinen CMS-toiminallisuus hämmentää käyttäjän roolia. Rekisteröityneenä käyttäjänä ei oikein hahmota onko ravintoloitsijan vai asiakkaan roolissa

## Koodi

- Koodi on selkeästi organisoitua, hienoa!
- SSR tekee hyvää hakukoneoptimoinnille
- Tämän tiedon voisi siirtää ympäristömuuttujaan, kuten esim. `process.env.STATIC_FORMS_ACCESS_KEY`: https://github.com/jaakkolantero/fullstackopen_project/blob/master/www/components/OrderDetails/CheckoutModal.tsx#L29
- Tämän voisi abstraktoida esim. `staticFormsClient` serviceen: https://github.com/jaakkolantero/fullstackopen_project/blob/master/www/components/OrderDetails/CheckoutModal.tsx#L43
- Jokusen testin voisi kirjoittaa

## Kokonaisuus

- Sovelluksessa on hyvä käytettävyys ja olennaisin toiminnallisuus on toteutettu
- Koodi on hyvin organisoitua ja hyvälaatuista
- Komponenteissa on paikoitellen melko paljon sovelluslogiikka, joka vaikeuttaa etenkin testausta, mutta myös ylläpidettävyyttä

**Comment by jaakkolantero** [comment]
Kiitos kommenteista @Kaltsoon. Hyviä huomioita ja osan ongelmista tiedostinkin, mutta projektin rajaus meni hieman pieleen ja tunnit eivät riittäneet kaikkien ominaisuuksien loppuunsaattamiseen.

**Comment by Kaltsoon** [comment]
Se on ymmärrettävää, kaikki parannusehdotukset ovat täysin _vapaaehtoisia_. Hyvää työtä!
